FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["src/Aegis.Common/Aegis.Common.csproj", "src/Aegis.Common/"]
COPY ["src/Aegis.Data/Aegis.Data.csproj", "src/Aegis.Data/"]
COPY ["src/Aegis.BotApi/Aegis.BotApi.csproj", "src/Aegis.BotApi/"]

RUN dotnet restore "src/Aegis.BotApi/Aegis.BotApi.csproj"

COPY . .
WORKDIR "/src/src/Aegis.BotApi"
RUN dotnet publish "Aegis.BotApi.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
EXPOSE 5000

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Aegis.BotApi.dll"]
