"""Protocol constants used by the Python client."""


class ProtocolConstants:
    MAGIC = 0xAE6C5D7

    VERSION_MAJOR = 1
    VERSION_MINOR = 0

    HEADER_SIZE = 4 + 1 + 1 + 1 + 2 + 8 + 4  # 21 bytes
    MAC_SIZE = 32
    MAX_MESSAGE_SIZE = 1024 * 1024
    MAX_PAYLOAD_SIZE = MAX_MESSAGE_SIZE - HEADER_SIZE - MAC_SIZE

    TYPE_UNKNOWN = 0
    TYPE_AUTH = 1
    TYPE_PING = 2
    TYPE_MESSAGE = 3
    TYPE_ACK = 4
    TYPE_ERROR = 5
    TYPE_HANDSHAKE = 6
    TYPE_NACK = 7
    TYPE_RETRANSMIT_REQUEST = 8
    TYPE_USER_PRESENCE = 9
    TYPE_GROUP_MESSAGE = 10
    TYPE_GROUP_CREATE = 11
    TYPE_GROUP_LEAVE = 12
    TYPE_CHANNEL_MESSAGE = 13
    TYPE_CHANNEL_CREATE = 14
    TYPE_CHANNEL_JOIN = 15
    TYPE_CHANNEL_LEAVE = 16
    TYPE_PRIVATE_CHAT_MESSAGE = 17
    TYPE_USER_SEARCH = 18
    TYPE_USER_SEARCH_RESULT = 19
    TYPE_REGISTER = 20
    TYPE_REGISTER_RESPONSE = 21
    TYPE_PROFILE_UPDATE = 22
    TYPE_PROFILE_UPDATE_RESPONSE = 23
    TYPE_PROFILE_GET = 24
    TYPE_PROFILE_GET_RESPONSE = 25
    TYPE_MESSAGE_EDIT = 26
    TYPE_MESSAGE_EDIT_RESPONSE = 27
    TYPE_MESSAGE_DELETE = 28
    TYPE_MESSAGE_DELETE_RESPONSE = 29
    TYPE_CHANNEL_EDIT = 30
    TYPE_CHANNEL_EDIT_RESPONSE = 31
    TYPE_GROUP_EDIT = 32
    TYPE_GROUP_EDIT_RESPONSE = 33
    TYPE_MEMBER_ROLE_UPDATE = 34
    TYPE_MEMBER_ROLE_UPDATE_RESPONSE = 35
    TYPE_MEMBER_PERMISSION_UPDATE = 36
    TYPE_MEMBER_PERMISSION_UPDATE_RESPONSE = 37
    TYPE_GROUP_MESSAGE_SEND = 38
    TYPE_GROUP_MESSAGE_RESPONSE = 39
    TYPE_GROUP_CREATE_RESPONSE = 40
    TYPE_CHAT_LIST_REQUEST = 41
    TYPE_CHAT_LIST_RESPONSE = 42
    TYPE_PRIVATE_CHAT_HISTORY_REQUEST = 43
    TYPE_PRIVATE_CHAT_HISTORY_RESPONSE = 44
    TYPE_CHANNEL_HISTORY_REQUEST = 45
    TYPE_CHANNEL_HISTORY_RESPONSE = 46
    TYPE_PRIVATE_CHAT_MESSAGE_EVENT = 47
    TYPE_CHANNEL_MESSAGE_EVENT = 48

    FLAG_NONE = 0x00
    FLAG_REQUIRES_ACK = 0x01
    FLAG_IS_RETRANSMIT = 0x02
    FLAG_COMPRESSED = 0x04
    FLAG_ENCRYPTED = 0x08
    FLAG_PRIORITY = 0x10

    ACK_OK = 0
    ACK_ERROR = 1
    ACK_RETRY = 2
    ACK_NOT_IMPLEMENTED = 3
